# This workflow is to create a release with prebuilt create_llvm_prof binary.
name: Create Release Build

on:
  release:
    types: [created]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:

    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{github.token}}
    - shell: bash
      run: |
        echo "Found release ${{steps.get_release.outputs.tag_name}}"
        echo "HTML URL: ${{steps.get_release.outputs.html_url}}"
        echo "Upload URL: ${{steps.get_release.outputs.upload_url}}"

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        ref: '${{github.ref}}'

    - name: Install Dependencies
      run: sudo apt-get -y install libunwind-dev libgflags-dev libssl-dev libelf-dev protobuf-compiler libzstd-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_TOOL=LLVM -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S ${{github.workspace}}

    - name: Build
      # Build your program with the given configuration
      run: make -C ${{github.workspace}}/build -j8

    - name: Run Tests
      run: make -C ${{github.workspace}}/build test

    - name: Create Zip Package
      run: |
        zip --junk-paths create_llvm_prof-x86_64-${{github.ref_name}}.zip ${{github.workspace}}/build/create_llvm_prof

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.get_release.outputs.upload_url}}
        asset_path: create_llvm_prof-x86_64-${{github.ref_name}}.zip
        asset_name: create_llvm_prof-x86_64-${{github.ref_name}}.zip
        asset_content_type: application/zip
